In [1]:
import numpy as np
import copy
import random
from scipy.optimize import minimize

In [2]:
#This will be the rosenbrock function
#using a = 1 and b = 100 for this test because that is a known value minimum (1, 1) and z is 0
f = lambda x0: (1 - x0[0])**2 + (100*((x[1] - x[0]**2)**2))

#Starting x and y
x = np.array([4*random.random() - 2, 4*random.random()-2])
print(x)
copyX = copy.deepcopy(x)
print(copyX)

#So for the gradient descent, you need to create a Hessian Matrix of the function
#This will be that hessian
#|2-400y+1200x**2     -400x|
#|                         |
#|-400x                 200|

j = 2 - (400 * x[1]) + (1200*(x[0]**2))
k = -400 * x[0] 
l = -400 * x[0]
m = 200

#But now I need to do and inverse
#|200                 +400x|
#|                         |
#|+400x     2-400y+1200x**2|


dM = copy.deepcopy(m)
dK = copy.deepcopy(k)
dL = copy.deepcopy(l)
dJ = copy.deepcopy(j)

m *= (1/((dJ*dM) - (dK*dL)))
k *= (-1/((dJ*dM) - (dK*dL)))
l *= (-1/((dJ*dM) - (dK*dL)))
j *= (1/((dJ*dM) - (dK*dL)))

H = np.array([[m, k], [l, j]]) #This is the hessian for the quasi-newtonian descent

[-0.24486867  1.88900106]
[-0.24486867  1.88900106]


In [3]:
print(H)

[[-0.00137058  0.00067123]
 [ 0.00067123  0.00467128]]


In [4]:
#The hessian in this case will be multiplied by a gradient of the function, which can be represented as a vector
#|-2a+2x-4byx+4x**3b|
#|                  |
#|2by-2x**2         |
grad = np.array([-2+(2*x[0])-(4*100*x[1]*x[0])+(4*100*x[0]**3), (2*100*x[1])-(2*x[0]**2)])
print(grad)

[176.66014164 377.680291  ]


In [5]:
#So the equation looks like this
#x(n+1) = x(n) - H*grad(x(n))
#And you keep checking the gradient to see if it equals zero, which is found with the sum of the
#square of each component in the gradient

q=0
while grad[0]**2 + grad[1]**2 > 1e-5:
    nextX = x - np.matmul(H, grad)
    
    
    print(nextX)
    #Reassign the new matrix
    j = 2 - (400 * nextX[1]) + (1200*(nextX[0]**2))
    k = 400 * nextX[0] 
    l = 400 * nextX[0]
    m = 200
    
    dM = copy.deepcopy(m)
    dK = copy.deepcopy(k)
    dL = copy.deepcopy(l)
    dJ = copy.deepcopy(j)

    m *= (1/((dJ*dM) - (dK*dL)))
    k *= (1/((dJ*dM) - (dK*dL)))
    l *= (1/((dJ*dM) - (dK*dL)))
    j *= (1/((dJ*dM) - (dK*dL)))
    
    H = np.array([[m, k], [l, j]])
    
    #Reassigning the gradient
    grad = np.array([-2+(2*nextX[0])-(4*100*nextX[1]*nextX[0])+(4*100*nextX[0]**3), (2*100*nextX[1])-(2*nextX[0]**2)])
    
    #Reassigning the x
    x = nextX
    
    print(H, grad)
    print("Iteration")
    q+=1

[-0.25625001  0.00617347]
[[ 0.03876534 -0.01986724]
 [-0.01986724  0.01518196]] [-8.61028624  1.1033658 ]
Iteration
[ 0.09945151 -0.18164039]
[[0.01272064 0.00253017]
 [0.00253017 0.00550326]] [  5.81812214 -36.34785982]
Iteration
[0.11740768 0.00367044]
[[0.16540822 0.03884039]
 [0.03884039 0.01412032]] [-1.29019441  0.70651925]
Iteration
[0.30337496 0.04380582]
[[0.04696551 0.02849632]
 [0.02849632 0.02229014]] [4.45952602 8.5770912 ]
Iteration
[-0.15048452 -0.27445884]
[[ 0.00827528 -0.0024906 ]
 [-0.0024906   0.00574959]] [-20.18481682 -54.9370597 ]
Iteration
[-0.12027591 -0.0088654 ]
[[ 0.08824039 -0.02122639]
 [-0.02122639  0.01010605]] [-3.36304825 -1.80201284]
Iteration
[ 0.13823056 -0.06203954]
[[0.02902009 0.00802293]
 [0.00802293 0.00721803]] [  2.76327198 -12.44612358]
Iteration
[0.1578945  0.00562739]
[[0.10286677 0.03248419]
 [0.03248419 0.01525815]] [-0.46505824  1.07561665]
Iteration
[0.17079299 0.00432251]
[[0.08375845 0.02861071]
 [0.02861071 0.01477302]] [0.0391137 

 [0.03790553 0.01950408]] [-0.06873095  3.2001174 ]
Iteration
[ 0.07682542 -0.04344345]
[[0.04600189 0.00706823]
 [0.00706823 0.00608604]] [-0.32995092 -8.70049338]
Iteration
[0.15350087 0.01184027]
[[0.14950143 0.0458972 ]
 [0.0458972  0.01909052]] [-0.97324819  2.32092861]
Iteration
[0.19247874 0.0122019 ]
[[0.08376285 0.03224514]
 [0.03224514 0.01741301]] [0.29790098 2.36628401]
Iteration
[ 0.09122455 -0.03860808]
[[0.04814173 0.00878342]
 [0.00878342 0.00660253]] [-0.1050837  -7.73825933]
Iteration
[0.16425182 0.01340698]
[[0.13461355 0.04422104]
 [0.04422104 0.01952677]] [-0.77982706  2.62743829]
Iteration
[ 0.15303905 -0.00341365]
[[0.07853091 0.02403659]
 [0.02403659 0.01235707]] [-0.0512253  -0.72957143]
Iteration
[0.17459823 0.006833  ]
[[0.08725535 0.03046926]
 [0.03046926 0.01563976]] [1.00325651e-03 1.30563138e+00]
Iteration
[ 0.13472907 -0.01361732]
[[0.0679916  0.01832089]
 [0.01832089 0.00993671]] [-0.01844542 -2.75976859]
Iteration
[0.18654463 0.01414364]
[[0.09744592 0

In [6]:
print(x)
print(q)

[0.16178713 0.00027026]
447


In [7]:
f(x)

0.7697067659143537

In [10]:
print(copyX)
res = minimize(f, copyX, method='CG', tol=1e-4, options={'disp': True})

[-0.24486867  1.88900106]
Optimization terminated successfully.
         Current function value: 0.067106
         Iterations: 2
         Function evaluations: 12
         Gradient evaluations: 4
